#!/usr/bin/env python3
"""Generate SchemaFiles.h - embeds .sql files as C++ raw string literals."""
import sys, os

sql_dir  = sys.argv[1]
out_file = sys.argv[2]

sql_files = sorted(f for f in os.listdir(sql_dir) if f.endswith('.sql'))

out = ['// AUTO-GENERATED by scripts/gen_schema_files.py — do not edit.',
       '#pragma once', '#include <string>', '#include <map>',
       'namespace Rosenholz { namespace SchemaFiles {',
       'inline const std::map<std::string,std::string>& all() {',
       '  static const std::map<std::string,std::string> s = {']

for fname in sql_files:
    name = fname[:-4]
    content = open(os.path.join(sql_dir, fname), encoding='utf-8').read()
    # Use R"SQLEOF(...)SQLEOF" raw string literal — safe for all SQL content
    # The delimiter SQLEOF won't appear in any SQL file
    out.append(f'    {{"{name}", R"SQLEOF(\n{content})SQLEOF"}},')
    print(f'  Embedded {fname} ({len(content)} bytes)', file=sys.stderr)

out += ['  };', '  return s;', '}',
        'inline std::string get(const std::string& name) {',
        '  auto& m=all(); auto it=m.find(name);',
        '  return it!=m.end()?it->second:"";', '}',
        '} } // namespace Rosenholz']

os.makedirs(os.path.dirname(out_file), exist_ok=True)
open(out_file, 'w').write('\n'.join(out) + '\n')
print(f'Written: {out_file} ({len(out)} lines)', file=sys.stderr)
