
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/nix/store/wiya2zqayp3yxsqwmanm1pb43alawdwa-clion-2025.3.1/clion/bin/cmake/linux/x64/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/nix/store/sj06kbqb6s7vn0jba1nw7vrip3av9spv-jetbrains-jdk-jcef-21.0.9-b1163.86/bin/"
      - "/nix/store/wkkwxc04gdw6b263l1h29pjarjnjdyb6-coreutils-9.8/bin/"
      - "/nix/store/d4c56s8wa6rz2dnw6ridg7r1dvax1gky-gnugrep-3.12/bin/"
      - "/nix/store/5k4mv2a1qrciv12wywlkgpslc6swyv58-which-2.23/bin/"
      - "/nix/store/9kg1njp3xpkg9lf4bi9llvh69qdbd3wv-git-2.51.2/bin/"
      - "/nix/store/im5106h2hx9al158rz6bfa4zbmbidim7-bash-interactive-5.3p3/bin/"
      - "/nix/store/w7j4a0ii09hjqxvri53f1h0h5cfbn04y-patchelf-0.15.2/bin/"
      - "/nix/store/0j1ajvl2qwwb9n5a91hzd0j98fk9fa3k-gcc-wrapper-14.3.0/bin/"
      - "/nix/store/k3qc3y1f6i8g2dgz5z0cf00dj4xc5rrv-gcc-14.3.0/bin/"
      - "/nix/store/hayjsz88980xx001qk2bbmcma11jww0y-glibc-2.40-218-bin/bin/"
      - "/nix/store/rinxh4y0akcin90l05j0zr1r3wahl34d-binutils-wrapper-2.44/bin/"
      - "/nix/store/sfjv70z6qr9mlf94zkjm9nw6bsdbplq1-binutils-2.44/bin/"
      - "/nix/store/dx1zhzy951phnqyixy0z77s0gcp6wc2z-cmake-4.1.2/bin/"
      - "/nix/store/7ivwij84bkixylkapyypb5and5dlc73n-gnumake-4.4.1/bin/"
      - "/nix/store/x06h0jfzv99c3dmb8pj8wbmy0v9wj6bd-pkg-config-wrapper-0.29.2/bin/"
      - "/nix/store/28vqy6w3pi18wy12gd4fr3k7if1ba4j6-sqlite-3.50.4-bin/bin/"
      - "/nix/store/9j8kdx5blrdpr0vz4vni6mmccbm6547w-lmdb-0.9.33-bin/bin/"
      - "/nix/store/wlnxvcy7my7kc3lf3czrmsm76mpbdciz-openssl-3.6.1-bin/bin/"
      - "/nix/store/y07607nm6364qqhc1gkkyiy48r1l2ndw-ncurses-6.5-dev/bin/"
      - "/nix/store/xp8g8298vbm4k9ipj14xf1r4rh899hr4-ncurses-6.5/bin/"
      - "/nix/store/n9fnrm5771ppfnd7rxnvcp6y5viivixp-readline-8.3p1/bin/"
      - "/nix/store/44rn0p64x92bnnh7cwn6x6ybvflybmvz-python3-3.13.12/bin/"
      - "/nix/store/5xwvdb1gdf1nrn7b41iji2pf9yb45xqm-gdb-16.3/bin/"
      - "/nix/store/n8f8909h56bmdch4p4cbsby3xisw8zlb-valgrind-3.26.0/bin/"
      - "/nix/store/bb1ipjfz8g6cir41rr0zc2x2ah43kzar-findutils-4.10.0/bin/"
      - "/nix/store/41d166ibs46jdcfg9x50ah2bhnwl12q1-diffutils-3.12/bin/"
      - "/nix/store/0zqnw11n1hk8mflzzvrz7sv1rm1cbnp8-gnused-4.9/bin/"
      - "/nix/store/y39kdg7y0zcmbsz8knkwkavcw82y2hn6-gawk-5.3.2/bin/"
      - "/nix/store/i8hncwf8234flnbgi2z19bzy4hjwhss1-gnutar-1.35/bin/"
      - "/nix/store/aj83nj8s5if1qb8zbxp7383dnza3rq33-gzip-1.14/bin/"
      - "/nix/store/wlq4waybfv4gp3g1940cavkv7lhxr5hp-bzip2-1.0.8-bin/bin/"
      - "/nix/store/mjkgsjcnc067wagr8qy467h1kdz1iiqp-gnumake-4.4.1/bin/"
      - "/nix/store/6ph0zypyfc09fw6hlc1ygjvk2hv4j9vd-bash-5.3p3/bin/"
      - "/nix/store/340ldxlqnipb3032grsgnpixflx5s97l-patch-2.8/bin/"
      - "/nix/store/90wmya07rpvnp89hg01llq8jy4zps3d7-xz-5.8.1-bin/bin/"
      - "/nix/store/jj0zadqjxjsffml5j9cmgm0xirh5l7jp-file-5.45/bin/"
      - "/run/wrappers/bin/"
      - "/home/jeandarq0ne/.nix-profile/bin/"
      - "/nix/profile/bin/"
      - "/home/jeandarq0ne/.local/state/nix/profile/bin/"
      - "/etc/profiles/per-user/jeandarq0ne/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/run/current-system/sw/bin/"
      - "/nix/store/wiya2zqayp3yxsqwmanm1pb43alawdwa-clion-2025.3.1/clion/bin/ninja/linux/x64/"
      - "/bin/"
      - "/usr/bin/"
      - "/usr/local/bin/"
    searched_directories:
      - "/nix/store/sj06kbqb6s7vn0jba1nw7vrip3av9spv-jetbrains-jdk-jcef-21.0.9-b1163.86/bin/uname"
    found: "/nix/store/wkkwxc04gdw6b263l1h29pjarjnjdyb6-coreutils-9.8/bin/uname"
    search_context:
      ENV{PATH}:
        - "/nix/store/sj06kbqb6s7vn0jba1nw7vrip3av9spv-jetbrains-jdk-jcef-21.0.9-b1163.86/bin"
        - "/nix/store/wkkwxc04gdw6b263l1h29pjarjnjdyb6-coreutils-9.8/bin"
        - "/nix/store/d4c56s8wa6rz2dnw6ridg7r1dvax1gky-gnugrep-3.12/bin"
        - "/nix/store/5k4mv2a1qrciv12wywlkgpslc6swyv58-which-2.23/bin"
        - "/nix/store/9kg1njp3xpkg9lf4bi9llvh69qdbd3wv-git-2.51.2/bin"
        - "/nix/store/im5106h2hx9al158rz6bfa4zbmbidim7-bash-interactive-5.3p3/bin"
        - "/nix/store/w7j4a0ii09hjqxvri53f1h0h5cfbn04y-patchelf-0.15.2/bin"
        - "/nix/store/0j1ajvl2qwwb9n5a91hzd0j98fk9fa3k-gcc-wrapper-14.3.0/bin"
        - "/nix/store/k3qc3y1f6i8g2dgz5z0cf00dj4xc5rrv-gcc-14.3.0/bin"
        - "/nix/store/hayjsz88980xx001qk2bbmcma11jww0y-glibc-2.40-218-bin/bin"
        - "/nix/store/rinxh4y0akcin90l05j0zr1r3wahl34d-binutils-wrapper-2.44/bin"
        - "/nix/store/sfjv70z6qr9mlf94zkjm9nw6bsdbplq1-binutils-2.44/bin"
        - "/nix/store/dx1zhzy951phnqyixy0z77s0gcp6wc2z-cmake-4.1.2/bin"
        - "/nix/store/7ivwij84bkixylkapyypb5and5dlc73n-gnumake-4.4.1/bin"
        - "/nix/store/x06h0jfzv99c3dmb8pj8wbmy0v9wj6bd-pkg-config-wrapper-0.29.2/bin"
        - "/nix/store/28vqy6w3pi18wy12gd4fr3k7if1ba4j6-sqlite-3.50.4-bin/bin"
        - "/nix/store/9j8kdx5blrdpr0vz4vni6mmccbm6547w-lmdb-0.9.33-bin/bin"
        - "/nix/store/wlnxvcy7my7kc3lf3czrmsm76mpbdciz-openssl-3.6.1-bin/bin"
        - "/nix/store/y07607nm6364qqhc1gkkyiy48r1l2ndw-ncurses-6.5-dev/bin"
        - "/nix/store/xp8g8298vbm4k9ipj14xf1r4rh899hr4-ncurses-6.5/bin"
        - "/nix/store/n9fnrm5771ppfnd7rxnvcp6y5viivixp-readline-8.3p1/bin"
        - "/nix/store/44rn0p64x92bnnh7cwn6x6ybvflybmvz-python3-3.13.12/bin"
        - "/nix/store/5xwvdb1gdf1nrn7b41iji2pf9yb45xqm-gdb-16.3/bin"
        - "/nix/store/n8f8909h56bmdch4p4cbsby3xisw8zlb-valgrind-3.26.0/bin"
        - "/nix/store/wkkwxc04gdw6b263l1h29pjarjnjdyb6-coreutils-9.8/bin"
        - "/nix/store/bb1ipjfz8g6cir41rr0zc2x2ah43kzar-findutils-4.10.0/bin"
        - "/nix/store/41d166ibs46jdcfg9x50ah2bhnwl12q1-diffutils-3.12/bin"
        - "/nix/store/0zqnw11n1hk8mflzzvrz7sv1rm1cbnp8-gnused-4.9/bin"
        - "/nix/store/y39kdg7y0zcmbsz8knkwkavcw82y2hn6-gawk-5.3.2/bin"
        - "/nix/store/i8hncwf8234flnbgi2z19bzy4hjwhss1-gnutar-1.35/bin"
        - "/nix/store/aj83nj8s5if1qb8zbxp7383dnza3rq33-gzip-1.14/bin"
        - "/nix/store/wlq4waybfv4gp3g1940cavkv7lhxr5hp-bzip2-1.0.8-bin/bin"
        - "/nix/store/mjkgsjcnc067wagr8qy467h1kdz1iiqp-gnumake-4.4.1/bin"
        - "/nix/store/6ph0zypyfc09fw6hlc1ygjvk2hv4j9vd-bash-5.3p3/bin"
        - "/nix/store/340ldxlqnipb3032grsgnpixflx5s97l-patch-2.8/bin"
        - "/nix/store/90wmya07rpvnp89hg01llq8jy4zps3d7-xz-5.8.1-bin/bin"
        - "/nix/store/jj0zadqjxjsffml5j9cmgm0xirh5l7jp-file-5.45/bin"
        - "/run/wrappers/bin"
        - "/home/jeandarq0ne/.nix-profile/bin"
        - "/nix/profile/bin"
        - "/home/jeandarq0ne/.local/state/nix/profile/bin"
        - "/etc/profiles/per-user/jeandarq0ne/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/run/current-system/sw/bin"
        - "/nix/store/wiya2zqayp3yxsqwmanm1pb43alawdwa-clion-2025.3.1/clion/bin/ninja/linux/x64"
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/wiya2zqayp3yxsqwmanm1pb43alawdwa-clion-2025.3.1/clion/bin/cmake/linux/x64/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.12.76 - x86_64
...
